### ISSUE TITLE
运行报错问题

### ISSUE THREAD

**Issue by kbk12** [wujcan/SGL-TensorFlow#33]
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    model = MyClass(sess, dataset, conf)
  File "/home/xgxy/KB/SGL-TensorFlow-main/model/general_recommender/SGL.py", line 25, in __init__
    super(SGL, self).__init__(dataset, conf)
  File "/home/xgxy/KB/SGL-TensorFlow-main/model/AbstractRecommender.py", line 34, in __init__
    num_thread=conf["num_thread"])
  File "/home/xgxy/KB/SGL-TensorFlow-main/util/tool.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/home/xgxy/KB/SGL-TensorFlow-main/evaluator/proxy_evaluator.py", line 84, in __init__
    num_thread=num_thread)
  File "/home/xgxy/KB/SGL-TensorFlow-main/util/tool.py", line 177, in wrapper
    bound_values = sig.bind(*args, **kwargs)
  File "/home/xgxy/.conda/envs/kb/lib/python3.6/inspect.py", line 2997, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/home/xgxy/.conda/envs/kb/lib/python3.6/inspect.py", line 2938, in _bind
    arg=param.name)) from None
TypeError: multiple values for argument 'metric'

**Comment by wujcan** [comment]
应该是给metric传参的时候传入了多个value，注意采用以下形式：--metric=["Precision", "Recall", "NDCG", "MAP", "MRR"]

**Comment by kbk12** [comment]
直接下载的然后想跑一下，就报这个错误，没有进行任何改动，找到配置文件metric=["Precision", "Recall", "NDCG", "MAP", "MRR"]，是正确的，请问还有其他注意的地方吗

**Comment by wujcan** [comment]
> 
首先比对下NeuRec.properties里面metric附近的内容是否正确，如果没问题，建议单步调试到出错的地方，监控下key和value的值看是不是正常读入

**Comment by lxy21214** [comment]
evaluator/backend/python/uni_evaluator.py
里面UniEvaluator的定义是
``` python
def __init__(self, user_train_dict, user_test_dict, user_neg_test=None,
                 metric=None, top_k=50, batch_size=1024, num_thread=8):
```
这和evaluator/backend/cpp/uni_evaluator.py里面UniEvaluator的定义不一致
``` python
def __init__(self, dataset, user_train_dict, user_test_dict, user_neg_test=None,
                 metric=None, top_k=50, batch_size=1024, num_thread=8):
```

evaluator/backend/__init__.py中的代码会根据情况选择加载哪个版本：
``` python
try:
    from evaluator.backend.cpp.uni_evaluator import UniEvaluator
    print("Evaluate model with cpp")
except:
    from evaluator.backend.python.uni_evaluator import UniEvaluator
    print("Evaluate model with python")
```

这导致evaluator/proxy_evaluator.py 中81行UniEvaluator的行为存在歧义。
正确编译cpp版本时应当没问题，但是cpp编译失败后，python版本也一定是运行失败的。
